### ISSUE TITLE
Issues vectorizing TeX

### ISSUE THREAD

**Issue by jjttyy27** [Jonathan-LeRoux/IguanaTex#10]
Hi,

I'm having some issues with vectorizing the TeX output. In the process of vectorizing, it seems to hang up in tex2img and stop after a minute. However, the EMF file is in fact created in the Temp folder, and I am able to import it using the "Insert vector graphics file" option, although it is not the correct size. 

Outside of IguanaTeX, I haven't been able to get tex2img to work properly, but for different reasons. When I try to compile
`\documentclass{article}`
`\usepackage{amsmath}`
`\usepackage{amsfonts}`
`\begin{document}`
`$a$`
`\end{document}`
for example, the first error that I get is
> ! LaTeX Error: This file needs format `pLaTeX2e' but this is `LaTeX2e'.

However, I'm not getting this error when using it through IguanaTeX. Thus I'm not sure if the issue is with tex2img or another step. If you have any advice on how to fix this it would be greatly appreciated.

I am using IguanaTex 1.56, 64 bit ghostscript 9.26, and tex2img 2.1.0.

**Comment by Jonathan-LeRoux** [comment]
Hi,

Have you tried running Tex2img once as a GUI (TeX2img.exe) first? Tex2img needs that step to setup the proper paths. It may also default to platex (the Japanese latex engine), and you may need to go into Options to change the latex engine.

Thanks,
Jonathan

**Comment by jjttyy27** [comment]
Yes, the error I mentioned concerning pLaTeX2e shows up when I run the code I posted in the tex2img GUI. I don't get this error when trying to vectorize the TeX in powerpoint. I just found the setting to fix the pLaTeX2e issue, so tex2img works fine now outside of powerpoint. So it seems like tex2img probably shouldn't be the issue. 

For reference, when vectorizing the last output of tex2img is

> C:\Users\MyName\AppData\Local\Temp>"C:\Program Files\gs\gs9.26\bin\gswin64c.exe" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dAutoRotatePages=/None -dCompatibilityLevel=1.5 -sOutputFile="ffndnjrk.pdf" -c ".setpdfwrite /stroke {strokepath fill} def" -f "c3zmzvtp.pdf"
GPL Ghostscript 9.26 (2018-11-20)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
Processing pages 1 through 1.
Page 1

> C:\Users\MyName\AppData\Local\Temp>"C:\Users\MyName\Downloads\TeX2img_2.1.0\TeX2img\pdfiumdraw.exe" --extent=50 --emf --transparent --pages=1 --output="ffndnjrk-%d.emf" "ffndnjrk.pdf"

> output: C:\Users\MyName\AppData\Local\Temp\ffndnjrk-1.emf

**Comment by Jonathan-LeRoux** [comment]
In Iguanatex, you should be using tex2imgc.exe, with a "c", is that the case?

**Comment by jjttyy27** [comment]
Thanks, that was the final issue. Everything (more or less) seems to work fine now. Sorry for my really late response.
