### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by TingxunShi** [Jonathan-LeRoux/IguanaTex#14]
Hi, 

I installed the plugin and tried but when I clicked "generate", I was always prompted that there is an encoding issue, no matter which latex engine I used. I checked the temp file located in the temp directory, only saw a file containing non-sense characters (seems generated a binary file). Could you please kindly help?

I'm using Win 10 and PowerPoint 2016, both are Chinese version

Here is a clipped snippet from the bulk error message (using the default latex-dvi engine):

```
The document does not appear to be in UTF-8 encoding.
Try adding \UseRawInputEncoding as the first line of the file
or specify an encoding such as \usepackage [latin1]{inputenc}
in the document preamble.
Alternatively, save the file in UTF-8 using your editor or another tool


! Package inputenc Error: Unicode character 
 (U+000B)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.4 ...顼]辒X墖Iら?倻玘?W兀{畨楰篂wy運遥此?
                                                  殗摯=3燕扛?GN=?%語...

You may provide a definition with
\DeclareUnicodeCharacter 


! Package inputenc Error: Invalid UTF-8 byte "AF.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              

``` 

My test code is quite simple

```Latex
\documentclass{article}
\usepackage{amsmath}
\pagestyle{empty}
\begin{document}

a + b = c

\end{document}
```

**Comment by Jonathan-LeRoux** [comment]
Hi,
This sounds like there's an issue when saving the file, and it may be difficult for me to debug as it's likely related to some locale setting on your end. Can you try checking "Debug" and see how the generated files look in the Temp folder?
Also, I'd suggest reposting your question to the [IguanaTex mailing list](https://groups.google.com/g/iguanatex), where others who also use the Chinese version of Windows and Office may provide feedback.
Thanks,
Jonathan

**Comment by TingxunShi** [comment]
Hi Jonathan,

Thanks for the replay. I switched to my personal laptop and seems everything goes fine (at least compiled successfully), so I doubt it's my office PC's issue. Ticket closed, thank you

Regards, Tingxun

**Comment by Jonathan-LeRoux** [comment]
Okay, good! If you figure out what the issue was, please let me know.
Thanks,
Jonathan
