### ISSUE TITLE
Mac Release

### ISSUE THREAD

**Issue by thomas-koller** [Jonathan-LeRoux/IguanaTex#19]
I did not find the Release directory as indicated in the README.md. Is it possible to compile the .ppam file for Mac from the sources?

**Comment by Jonathan-LeRoux** [comment]
My bad, there was a typo in the URL ("Release" shouldn't have been capitalized), it should be fixed now.
There's also a direct link under "Releases" (it says "1 Tags") in the side bar if you're on a desktop.

As to whether it's possible to compile everything from just the source code (.frm, .frx, .bas, ... files), I've never tried and my guess is that it is possible but not fun. You'd have to create a VBA project (.pptm) in PowerPoint and import all the modules and forms, and if that works you'd just have to export to .ppam. You'd also need to compile the IguanaTexHelper, but that should be straightforward. All in all, I don't advise it. The code is here mainly as a way to track changes, discuss issues, and for other developers to borrow from it if they see something useful.

Thanks,
Jonathan

**Comment by thomas-koller** [comment]
Hi Jonathan

Many thanks for the quick reply. Also my bad, I did check the tags, but did not see the release files. Everything seems to work now. Great job and many thanks again to this useful plugin! I am very happy to be able to combine powerpoint and latex, and now it works both on windows and Mac!

Cheers,
-Thomas


My bad, there was a typo in the URL ("Release" shouldn't have been capitalized), it should be fixed now.
There's also a direct link under "Releases" (it says "1 Tags") in the side bar if you're on a desktop.

As to whether it's possible to compile everything from just the source code (.frm, .frx, .bas, ... files), I've never tried and my guess is that it is possible but not fun. You'd have to create a VBA project (.pptm) in PowerPoint and import all the modules and forms, and if that works you'd just have to export to .ppam. You'd also need to compile the IguanaTexHelper, but that should be straightforward. All in all, I don't advise it. The code is here mainly as a way to track changes, discuss issues, and for other developers to borrow from it if they see something useful.

Thanks,
Jonathan
