### ISSUE TITLE
IguanaTex stopped working on Powerpoint MacOS

### ISSUE THREAD

**Issue by claudiacauli** [Jonathan-LeRoux/IguanaTex#21]
Using: 
- macOS Big Sur 11.5.2
- PowerPoint 16.53
- latest release installed following the readme.md

When I try to generate a LaTex display (even empty) I get the "Run-Time error 13 Type Mismatch" dialog. 
This happens with any latex compiler.  

<img width="522" alt="Screenshot 2021-09-18 at 17 54 21" src="https://user-images.githubusercontent.com/5575498/133894824-df9e683d-4047-43af-b151-0f5825232e95.png">

**Comment by Jonathan-LeRoux** [comment]
Did it use to work? If so, any possible change that could be related, e.g. OS/Office upgrade?

**Comment by claudiacauli** [comment]
It worked like a charm until some months ago.
I used it in January (I believe with a previous release) and worked. 
I tried again in June and something had broken (I don't remember what no). 
So, today, I re-installed it and I get this new error (different from the one that I had before). 

I must have updated PowerPoint in the meanwhile...

**Comment by Jonathan-LeRoux** [comment]
I am guessing you were using [Tsung-Ju's original Mac port](https://github.com/tsung-ju/IguanaTexMac/releases/tag/1.56-mac.3). You could try to install that version and see if it works.

Note that an empty display will likely lead to an error in the LaTeX compilation, so I wouldn't use that as a test case.

Could you maybe [download the .pptm file](https://github.com/Jonathan-LeRoux/IguanaTex/releases/download/v1.59/IguanaTex_v1_59.pptm), open it, then in Tools>Macro>Macros..., select NewLatexEquation (make sure IguanaTex_v1_59 is slected in "Macros in") and try creating a display there. This should give you the option to "Debug".
This should take you to the Visual Basic Editor, hopefully at the line where the issue occurs.
You could also create a breakpoint earlier and then step over (shift+command+O) or step into (shift+command+I) each line of code until something goes wrong.
One more thing you could do to try to understand what is going on is to set your temporary folder to some easily accessible folder on your computer, then drag-and-drop that folder over the Powerpoint app to give write access to all files in that folder (this will avoid you having to grant access to every single file multiple times). Doing so will allow you to inspect the temporary files. I'd like to know if the latex compilation even takes places.
You could also navigate to the temporary folder automatically determined by Powerpoint (you can see the path in the "Temp folder" text box of the main IguanaTex window where you create a display), but that path is very complicated, and copying from the IguanaTex window unfortunately doesn't work, so you'll have to navigate by hand.

Please let me know if you find anything.

**Comment by Jonathan-LeRoux** [comment]
Closing this as I haven't heard from original poster. I'm guessing this is due to an issue with installation specific to their setup.
