### ISSUE TITLE
An error window can't be close on Mac

### ISSUE THREAD

**Issue by Cqyiiii** [Jonathan-LeRoux/IguanaTex#24]
<img width="495" alt="image" src="https://user-images.githubusercontent.com/70658811/160241397-d1bc5e68-0959-4a55-9b23-180d225e485c.png">
Why this window can't be close and how I solve it?

**Comment by Jonathan-LeRoux** [comment]
I'm not sure why the Close button isn't working, it does work for me.
This seems to be triggered by the fact that IguanaTex cannot find the LaTeXiT-metadata executable. One workaround to get rid of that message would be for you to download [LaTeXiT-metadata-macos](https://github.com/Jonathan-LeRoux/IguanaTex/releases/download/v1.59/LaTeXiT-metadata-macos) and set its location in the Main Settings menu. Easiest way to do this is to click on the "..." button next to the LaTeXiT-metadata path textbox and navigate to the file you just downloaded. Please also make the downloaded file executable (`chmod +x LaTeXiT-metadata-macos` in the Terminal), which is not the case by default.

**Comment by zhoutengye** [comment]
When clicking on close, this window automatically appears again. I could do nothing on PowerPoint, even save the current file, the only thing I can do is to force quit. 

I am using Macbook Pro 2015, OS X 12.3.1, MS Office

**Comment by Jonathan-LeRoux** [comment]
Did you try the solution I suggested?

**Comment by zhoutengye** [comment]
> Did you try the solution I suggested?

Yes, I did. Usually, I do not see this error, but sometimes, this error appears, I do not know why. Whenever it happens, it becomes an error loop, the only way to quit this error is to force quit PowerPoint.

**Comment by Jonathan-LeRoux** [comment]
Do you see exactly the same error window as posted by @Cqyiiii ? Their error seemed to be that IguanaTex couldn't find the `LaTeXiT-metadata-macos` executable, so if the executable is in the right location, there shouldn't be a problem. If possible, please post a screenshot of the error window you are seeing.

In case you do have an issue with the `LaTeXiT-metadata-macos` executable not being found, could you try using [IguanaTex_v1_60_0.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/8343339/IguanaTex_v1_60_0.zip), the latest beta version, and copying `LaTeXiT-metadata-macos` under `/Library/Application Support/Microsoft/Office365/User Content.localized/Add-Ins.localized/`? You should be able to set the path in Main Settings to an empty string and it will default to this folder, or just navigate to the correct path using the "..." menu.

**Comment by zhoutengye** [comment]
> Do you see exactly the same error window as posted by @Cqyiiii ? Their error seemed to be that IguanaTex couldn't find the `LaTeXiT-metadata-macos` executable, so if the executable is in the right location, there shouldn't be a problem. If possible, please post a screenshot of the error window you are seeing.
> 
> In case you do have an issue with the `LaTeXiT-metadata-macos` executable not being found, could you try using [IguanaTex_v1_60_0.zip](https://github.com/Jonathan-LeRoux/IguanaTex/files/8343339/IguanaTex_v1_60_0.zip), the latest beta version, and copying `LaTeXiT-metadata-macos` under `/Library/Application Support/Microsoft/Office365/User Content.localized/Add-Ins.localized/`? You should be able to set the path in Main Settings to an empty string and it will default to this folder, or just navigate to the correct path using the "..." menu.

I am not sure. In these two days, I have not seen this error. But I am sure that whenever some the window like the error window posted by @Cqyiiii , I could do nothing to PowerPoint. The window kept on popping after clicking on close. I lost my unsaved PowerPoint, unfortunately. 

Your solution will prevent the window to appear, but I would recommend fixing the pop-up window issue when it appears, it should not keep on popping up after clicking on close.

**Comment by Jonathan-LeRoux** [comment]
I will close this for now, please feel free to reopen if you experience this issue again.
