### ISSUE TITLE
ImageMagick

### ISSUE THREAD

**Issue by pasafier** [Jonathan-LeRoux/IguanaTex#25]
ImageMagick uses magick.exe instead of convert.exe, at least for the current release. The IguanaTex install instructions refer to setting the path to convert.exe...

**Comment by Jonathan-LeRoux** [comment]
Thanks for letting me know, I will clarify. I hadn't realized that magick.exe fully replaced convert.exe. This would simplify the installation process as people wouldn't need to check the legacy executable box.

**Comment by Jonathan-LeRoux** [comment]
In the [v1.60 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.60), README has been clarified, and the user is now prompted to set the path to magick.exe. I just realized that I forgot to change the default path to magick.exe in the add-in, but that needs to be overwritten anyway. It will be in the next release.
