### ISSUE TITLE
Is there some easy way to generate individual text boxes at the same time

### ISSUE THREAD

**Issue by A6669** [Jonathan-LeRoux/IguanaTex#26]
When I use IguanaTex to input math formula, can I generate individual text boxes at the same time?
For example, I input $a=1$ $b=2$ $c=3$ then generate it, I get a single text book including $a=1$ $b=2$ $c=3$.
but I want three individual text boxes including $a=1$ $b=2$ $c=3$ respectively.
I know I can use IguanaTex three times to get this result, I just want to know whether there is easier way to get it.

**Comment by Jonathan-LeRoux** [comment]
That's a good question, and I don't see a way to do this easily with the current setup.

**Comment by A6669** [comment]
> 
thank you, if you have some way to figure it out, do not forget to tell me.
