### ISSUE TITLE
Enable --shell-escape

### ISSUE THREAD

**Issue by lcnittl** [Jonathan-LeRoux/IguanaTex#3]
Is there a way to enable --shell-escape for the chosen compiler?

**Comment by Jonathan-LeRoux** [comment]
It should already be enabled for all compilers (except TeX2img). What are you trying to do?

**Comment by lcnittl** [comment]
I was trying to include an `eps` graphic using `auto-pst-pdf`. But I just found that this is not a problem of IguanaTeX, but rather of the documentclass I'm using. With `article`-class, `graphicx` and `auto-pst-pdf` it is working fine.

Sorry for bothering

**Comment by Jonathan-LeRoux** [comment]
Thanks for the update, I'm glad you were able to make it work.
