### ISSUE TITLE
Bug: Failure to use any function in PowerPoint 2019 32-bit

### ISSUE THREAD

**Issue by ZheruQiu** [Jonathan-LeRoux/IguanaTex#31]
There is an issue using IguanaTeX v1.60 on PowerPoint 2019 32-bit running on Windows 10 21H1. When I click any button on the IguanaTeX ribbon, a warning message is shown as follow and nothing happens.

![image](https://user-images.githubusercontent.com/22540484/170239263-7a9fda45-ce75-4e23-aa3d-17f1fcc7d343.png)

Although this warning may suggest a security configuration problem, the same environment can run v1.59.1 without problem. Trying to run the macros in VBA, it seems a possible reason is the `LongLong` type used in these definitions are not supported on 32-bit PowerPoint

![image](https://user-images.githubusercontent.com/22540484/170240397-e986a375-1605-432e-84af-dcb691379ad2.png)

As a Windows user, I'm not sure about the functionality of these definitions, but one apparent workaround is to move these const definitions into the `#If Mac Then` block.

**Comment by Jonathan-LeRoux** [comment]
This should now be fixed with the v1.60.1 release, please double check!
