### ISSUE TITLE
Seeking help with installation

### ISSUE THREAD

**Issue by alexboche** [Jonathan-LeRoux/IguanaTex#35]
Hello,

I am having difficulty with installation.  I tried the manual approach described in the [readme](https://github.com/Jonathan-LeRoux/IguanaTex/blob/v1.60.2/README.md). 

On mac, when I go into powerpoint, and click on the add on, it says the dylib file is not found. But I think it is where it is supposed to be as I show in the terminal screen shot.

Can you please advise how to address this problem? 

Thank you!

<img width="1053" alt="Screen Shot 2022-08-17 at 8 47 01 AM" src="https://user-images.githubusercontent.com/44827758/185150746-2a280977-708c-413f-b5c3-311bf2ea9fc2.png">
<img width="584" alt="Screen Shot 2022-08-17 at 8 47 36 AM" src="https://user-images.githubusercontent.com/44827758/185150750-b516f361-163e-4288-a3cf-4398b27763e9.png">

**Comment by Jonathan-LeRoux** [comment]
Did you get a notification that the dylib was blocked? Take a look in the security settings to see if it appears there.
Also, what are the permissions on the dylib?

**Comment by tsung-ju** [comment]
You could also try the following command if the dylib didn't appear in the security setting. It has the same effect as unblocking the dylib in the Settings app.
```sh
sudo xattr -d com.apple.quarantine /Library/Application\ Support/Microsoft/Office365/User\ Content.localized/Add-Ins.localized/libIguanaTexHelper.dylib
```
