### ISSUE TITLE
Grant File Access (MacOS)

### ISSUE THREAD

**Issue by ssbodda** [Jonathan-LeRoux/IguanaTex#36]
Hi,

Every time I create a new equation or even try to edit the old one, it asks for grant access multiple times. I have installed the latest version. It was happening in previous versions as well. Can you please look into it? In the main settings, I am using the absolute path option.

![image](https://user-images.githubusercontent.com/32209558/185768403-5d1f1cad-445f-4472-9c0f-4b9929425d77.png)

**Comment by Jonathan-LeRoux** [comment]
The easiest workaround is to set the absolute path to an empty string in the main settings, and IguanaTex will then use the default sandbox folder, which doesn't require any permission.
If you really need to have the temp folder be set to something specific, I believe one way to grant access to the whole folder is to drag and drop the folder on top of the PowerPoint application. This will hopefully stick until you quit the app.

**Comment by ssbodda** [comment]
Thanks a ton, it worked!
