### ISSUE TITLE
Feature-request: Ability to parse formulas originally created with TeXPoint in IguanaTeX to reuse previous slides

### ISSUE THREAD

**Issue by stachnis** [Jonathan-LeRoux/IguanaTex#37]
IguanaTeX is awesome. Lots of people used TeXPoint before and created larger archives of slide (eg lecture coursework) with TeXPoint. It would be awesome if IguanaTeX could edit TeXPoint-created formuals (or convert them) so that one can migrate from TeXPoint to IguanaTeX without data loss. That would be so great. Thanks.

**Comment by Jonathan-LeRoux** [comment]
Well, IguanaTex can already do that!
Select a TexPoint display, click Edit, and it should allow you to edit it as an IguanaTex display. If the size becomes completely different, I suggest regenerating once with the option to fix the size, then modify the content.

**Comment by stachnis** [comment]
Man, you are the best. For some reason, this was not working for me but after trying it another file, it works. You made my day. Thanks!

**Comment by Jonathan-LeRoux** [comment]
That's great to hear!
