### ISSUE TITLE
Installation instructions for Windows

### ISSUE THREAD

**Issue by JakobHeiss** [Jonathan-LeRoux/IguanaTex#38]
I would recommend in the installation instructions under 1. to directly save the .ppam add-in into the folder `C:\Users\user_name\Appdata\Roaming\Microsoft\Addins` as mentioned in https://bytemeta.vip/index.php/repo/Jonathan-LeRoux/IguanaTex/issues/28, since Microsoft blocked IguaneTax when I saved it into the default Download-folder under Windows 11.

**Comment by Jonathan-LeRoux** [comment]
Thanks for the suggestion, I modified the Readme accordingly.
