### ISSUE TITLE
Generate Error Message

### ISSUE THREAD

**Issue by wenbo5565** [Jonathan-LeRoux/IguanaTex#4]
Hi, I am a windows8.1 users with Miktex has been installed (verified in cmd). However, when I was trying to generate formula, I got the attached error message and couldn't figure it out. Thank you

![image](https://user-images.githubusercontent.com/7663395/38158563-f97a091e-3464-11e8-9b08-c50a9f806111.png)

![image](https://user-images.githubusercontent.com/7663395/38158569-1b3f0bee-3465-11e8-8e3f-bc69846a2f1b.png)

**Comment by Jonathan-LeRoux** [comment]
What happens when you run that command in a cmd window (after cd-ing to c:\temp\)?
The command should be in your clipboard when it appears in the debug window, so you should be able to paste it in cmd.

**Comment by wenbo5565** [comment]
I restart my powerpoint today. It is working now. I don't change any of my formula in the editor.

**Comment by Jonathan-LeRoux** [comment]
There tends to be issues the first time the add-in is run after installing it or after installing LaTex, often requiring a reboot of the machine or a restart of powerpoint. I'm glad it's working now.

**Comment by wenbo5565** [comment]
I guess you are right. Thanks for coding up this tool and the help.
