### ISSUE TITLE
Add-in is blocked

### ISSUE THREAD

**Issue by YuhanLiuSYSU** [Jonathan-LeRoux/IguanaTex#42]
Hello! I have been using IguanaTex for some time until several days ago it was blocked by MS PowerPoint. I tried to remove and re-add it, but the error still occurs, as shown in the figure below. Could you help me resolve this problem? Thanks a lot!
![image](https://user-images.githubusercontent.com/39122759/196293217-105286cc-7b5a-4fb8-8473-7211876476ba.png)

**Comment by Jonathan-LeRoux** [comment]
Hi!

Could you take a look at the suggestions in https://github.com/Jonathan-LeRoux/IguanaTex/issues/28?

Thanks,
Jonathan

**Comment by YuhanLiuSYSU** [comment]
Thanks Jonathan! Putting it in the folder `Microsoft/Addins` solves this problem!
