### ISSUE TITLE
Macros. Add information to the webpage

### ISSUE THREAD

**Issue by parthe** [Jonathan-LeRoux/IguanaTex#43]
I use macros with IguanaTex, which are loaded from a `macros.sty` file in my Temp folder. My default code looks as below:

```
\documentclass{article}
\usepackage{macros}          % c:\temp\macros.sty
\pagestyle{empty}
\begin{document}
\begin{align*}

\end{align*}
\end{document}
```

This is a game changer and I will likely never go back to using beamer again.

Do you think we can add information about to use macros on the webpage of IguanaTex?

**Comment by Jonathan-LeRoux** [comment]
There was a brief mention on the [FAQ](https://www.jonathanleroux.org/software/iguanatex/faq.html) about macros. I expanded it a bit, not great but maybe slightly better :)
