### ISSUE TITLE
\Beta not defined

### ISSUE THREAD

**Issue by ProfNitz** [Jonathan-LeRoux/IguanaTex#44]
I just downloaded 1.60.2 and it seems that \Beta is not defined (all the other capital greek letter work fine)

sample code:
\documentclass{article}
\usepackage{amsmath}
\renewcommand{\d}{\mathrm{d}}
\pagestyle{empty}
\begin{document}

\begin{align*}
\delta &= \Delta\,\mathrm{e}^{st}\\
\dot{\psi} &= \dot{\Psi}\,\mathrm{e}^{st}\,\,
\mathrm{mit}\,\,\dot{\Psi} = G_{\delta\rightarrow\dot{\psi}}(s)\Delta\\
\beta &= \Beta
\end{align*}

\end{document}

error message
! Undefined control sequence.
<argument> ...{\psi }}(s)\Delta \\ \beta &= \Beta 
                                                  
l.12 \end{align*}

**Comment by Jonathan-LeRoux** [comment]
This is a LaTeX issue, not an IguanaTex issue. Some uppercase Greek letters are not defined, please see [this StackExchange question](https://tex.stackexchange.com/questions/485593/how-to-write-capital-alpha). \Beta is simply \mathrm{B}.
