### ISSUE TITLE
Enable constant write access OSX for IguanaTex_tmp.tmp

### ISSUE THREAD

**Issue by rudolfwilliam** [Jonathan-LeRoux/IguanaTex#47]
I see that Iguanatex creates this file called ` IguanaTex_tmp.tmp` in the folder that it needs access to. However, I struggle a bit with making it such that I do not have to grant access every single time I create an equation. The problem is that it seems to recreate the ` IguanaTex_tmp.tmp` file every time and then the access rights seems to be gone again. Does someone know how to deal with this? My internet research suggests ACL, but I am not very familiar with this. Is there a simpler solution?

**Comment by Jonathan-LeRoux** [comment]
There are two ways to deal with the Temp folder on Mac. 
The easiest is to let Iguanatex pick the temp folder by selecting Absolute and leaving the path empty. The Temp folder will be inside the PowerPoint sandbox and everything will work without having to give permissions.
If you need the Temp folder to be a specific folder outside the sandbox, then the best thing to do is to drag and drop that folder from the Finder on top of the PowerPoint application. This will allow you to give permission to the whole folder at least for the current session.
