### ISSUE TITLE
"pdflatex" is run instead of pdflatex

### ISSUE THREAD

**Issue by vivienlonde** [Jonathan-LeRoux/IguanaTex#48]
I have the following error:

Could not start process: ' "pdflatex" -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex '.
GetLastError returned 0.

Running the command from a shell without the quotes around "pdflatex" works:
pdflatex -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex

**Comment by Jonathan-LeRoux** [comment]
Do you mean that it only works without quotes in the shell? Are you on Mac or Windows?

**Comment by vivienlonde** [comment]
Hi ! Yes exactly: it only works without quotes. I am on Windows, using powershell.

This is the error that I get with quotes:
ParserError:
Line |
   1 |  "pdflatex" -output-format dvi -shell-escape -interaction=batchmode Ig …
     |             ~~~~~~~
     | Unexpected token '-output' in expression or statement.
     
Note that IguanaTex used to work well. I have this error since I installed a mandatory update on my machine.

Thank you for the quick answer above btw :)

**Comment by Jonathan-LeRoux** [comment]
Do you use PS as your default shell?
I would recommend trying to compile an IguanaTeX display with the Debug box checked. This will show you exactly what is run, and what the error is.

**Comment by vivienlonde** [comment]
Oh you're right: command prompt is my default shell. And in command prompt the command runs with quotes.

I now understand that the problem comes from a rule set by the administrator of my organization to “Block all Office applications from creating child processes”. I'll contact my administrator.

Thank you for the help. I'm closing this issue.

**Comment by Jonathan-LeRoux** [comment]
If your admin needs a self-signed version of the add-in, please let me know.

**Comment by MoWaelHamdy** [comment]
@vivienlonde , Hi there,
I am facing the same issue, may I know how did you solve it?

Thanks in advance,
Mohamed

**Comment by vivienlonde** [comment]
I haven't manage to solve the issue. Please let me know if you do. Thanks

**Comment by Jonathan-LeRoux** [comment]
Have you asked your admin if they could set some exclusions for specific processes?

**Comment by vivienlonde** [comment]
Yes I've asked but it didn't work :(

**Comment by MoWaelHamdy** [comment]
@Jonathan-LeRoux  @vivienlonde ,
Thanks for you both for taking from your time to offer help.
As a work around I write the equation I want in the tmp tex file then on the shell terminal I run the command pdflatex without the quotes then take a snippet from the DVI file.

**Comment by Jonathan-LeRoux** [comment]
@vivienlonde by "it didn't work", do you mean they tried to put an expiration in place and failed, or they refused to do it?
If they tried, any detail is appreciated.

**Comment by vivienlonde** [comment]
Hello @Jonathan-LeRoux , they refused to do it.

**Comment by Jonathan-LeRoux** [comment]
That's unfortunate, because the list of processes that they would need to allow is somewhat limited (various flavors of LaTeX, ImageMagick's magick.exe, etc). I can't see a workaround to that.
