### ISSUE TITLE
How do I set the correct aspect ratio for output latex box?

### ISSUE THREAD

**Issue by CyanideBoy** [Jonathan-LeRoux/IguanaTex#49]
I do not get to select how 'wide' the generated piece of latex pdf is. How can one change this? For example, if I I want the output to be a box of width equalling the entire slide width, then how do I achieve this? I can't simply scale the pdf/image since that changes the latex text size inside the box. 

To give some context, I am writing my PPT text in latext as well as there are way too many in-line math symbols. I just want the output pdf/image of text to be of the desired width.

**Comment by Jonathan-LeRoux** [comment]
It sounds like you need to determine the size of the page in your LaTeX document.
The simplest is to use `\textwidth=600pt` (or another value that suits your needs) in the preamble. Please see [this thread](https://groups.google.com/g/iguanatex/c/MfZ09McJ8fc/m/_s4f81tKAAAJ) for other suggestions.

**Comment by CyanideBoy** [comment]
Thanks a lot @Jonathan-LeRoux !
