### ISSUE TITLE
Runtime Error 13 - Type Mismatch

### ISSUE THREAD

**Issue by lcnittl** [Jonathan-LeRoux/IguanaTex#5]
As stated in the [FAQ](http://www.jonathanleroux.org/software/iguanatex/faq.html)

> Q: When launching PowerPoint 2016, I get a "Type Mismatch" error.
> 
> I know. This seems to only happen on some machines (my laptop is one, if that's any consolation), for an unknown reason, and this somehow does not trigger PowerPoint's debugger , so I don't know where this comes from. Everything seems normal after just clicking "OK". 

it can happen that a ["Type mismatch" error](https://www.computerhope.com/issues/ch000380.htm) happens when using IguanaTeX on different machines.

> 13 | Type Mismatch | Make  sure your system regional settings are setup correctly and that the  program you're running is made for your version of Windows.

I just found out that this can be due to a different "decimal symbol" setting (`'.'` vs `','`) within the region/customize format settings.

The error occurred when generating IguanaTeX content on a `'.'` system and opening on a `','` system.

After setting the `','` system to use `'.'` as decimal symbol, the error was gone.

**Comment by Jonathan-LeRoux** [comment]
I'm not sure I was talking about the same error in the FAQ. Are you getting this error when you start PowerPoint? That's the issue I have been having on my Windows 8.1 laptop. My system is set to use `'.'` as decimal symbol.
It sounds like you are getting the error when generating an IguanaTex display. If so, that's an error I hadn't heard of before.

**Comment by lcnittl** [comment]
I see. Yes, the error I get only occurs when trying to edit a LaTeX display with the `','` system that was originally created on the `'.'` system.

**Comment by Jonathan-LeRoux** [comment]
Thanks for confirming, I'll add a mention on the FAQ next time I update it!
