### ISSUE TITLE
chinese character can't show

### ISSUE THREAD

**Issue by leewi9** [Jonathan-LeRoux/IguanaTex#51]
```
\documentclass{article}
\usepackage{amsmath}
\usepackage{CJK}
\pagestyle{empty}

\begin{document}

\begin{CJK}{UTF8}{gbsn}

$$
\displaystyle
u_n(x)=
\begin{cases}
1& \text{[0,1]上的有理数} \\
0& \text{[0,1]上的无理数}
\end{cases}
$$

\end{CJK}

\end{document}

```

but generated picture only shows [0,1] 

the chinese character following doesn't show

**Comment by Jonathan-LeRoux** [comment]
Does this compile outside of IguanaTex?

**Comment by leewi9** [comment]
@Jonathan-LeRoux Thanks for the reply, It is inside the IguanaTex, by clicking "New Latex Display" and edit the content, then click "Generate"

**Comment by shengrihui** [comment]
I've encountered a similar issue. However, after switching the LaTeX engine to xelatex, the error no longer occurs. Nevertheless, it still doesn't generate Chinese characters.
@leewi9 请问你解决这个问题了吗？

**Comment by Jonathan-LeRoux** [comment]
My guess is that some fonts may be missing. I suggest trying to check the Debug box and see what happens. Also, please confirm that you do get the Chinese characters when compiling the same code outside IguanaTeX, just using your normal LaTeX editor on the same machine.

**Comment by shengrihui** [comment]
I solved the problem using [this method](https://blog.csdn.net/qq_34809033/article/details/80680280). I installed various packages and used `\documentclass[UTF8]{ctexart}`.

**Comment by Jonathan-LeRoux** [comment]
Thanks for the update and the link! I'll close this issue.
