### ISSUE TITLE
Suggestion: Add a fast preview button

### ISSUE THREAD

**Issue by kdtieste** [Jonathan-LeRoux/IguanaTex#56]
When editing latex using powerpoint I often need a preview of the latex result. 

Is it possible to add a preview button with the following function: 

Regenerate and continue editing? 

Instead of
Iguana: ReGenerate
Powerpoint: Select latex object, editLatexDisplay

So it would be much easier to edit a latex text, prewiew the result in poerpoint and continue editing. 

Thanks

**Comment by Jonathan-LeRoux** [comment]
I'm not sure I see what you have in mind. Could you maybe do a mockup picture?

**Comment by kdtieste** [comment]
![IguanaLayout](https://github.com/Jonathan-LeRoux/IguanaTex/assets/55718440/3091e03f-584b-4047-8fb9-e36293f1bdf6)
Either you implement an additional button, see picture.

Perhaps it is easier to change the function of the existing ReGenerate button to the update function then you can leave editing by clicking on Cancel.


Thanks

Karl-Dieter

**Comment by Jonathan-LeRoux** [comment]
I'm not sure this would fit well in the workflow, and that it would solve a frequent problem. After generating the display, I see three cases:
1. the user is happy: stop there
2. the user wants to tweak further from the current state: they can "edit" again
3. the user wants to tweak further, but needs to revert to the previous state for some reason: they can "edit", select all the LaTeX source they just generated (ctrl+a), cancel, and undo the generation (ctrl+z) to get back to the previous state.
It sounds to me like the purpose of preview would be to handle case 3, and I'm not sure it happens that often to warrant another solution than the one I described.
But I'll keep that in mind, maybe the idea will grow :)
