### ISSUE TITLE
"pdflatex" -shell-escape -interaction=batchmode IguanaTex_tmp.tex

### ISSUE THREAD

**Issue by shengrihui** [Jonathan-LeRoux/IguanaTex#57]
What‘s  this wrong?

Could not start process:""pdflatex"-shell-escape -interaction=batchmodeIguanaTex tmp.tex'.GetLastError returned 0

**Comment by Jonathan-LeRoux** [comment]
It could be many things, and it's hard to know without more context. Which OS, how you installed the addin, what you've tried so far...
First thing is to check the Debug box and see what happens.

**Comment by shengrihui** [comment]
I'm on Windows, and when I tried to generate my first LaTeX formula, a prompt popped up,
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/77373579/0ffe5422-2717-4782-90b5-c09844170841)
then,
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/77373579/9f5c3892-66d7-415d-9d78-fed0c7cc06f3)

**Comment by Jonathan-LeRoux** [comment]
Can you try to check the Debug box before generating?

**Comment by shengrihui** [comment]
![image](https://github.com/Jonathan-LeRoux/IguanaTex/assets/77373579/7fa98023-d43c-42c4-b789-75293b0d1759)
Is it like this?
After I click "continue", the previous prompt reappears.

**Comment by Jonathan-LeRoux** [comment]
Yes, please copy the command, open a command line (win+r cmd), cd to your temp folder (e:\temp), paste the command, and run it. That should tell you what is going wrong.

**Comment by shengrihui** [comment]
Thank you very much for your reply! I realized that many things were not pre-installed on my system😅. Now that I've installed them all, it is working fine!

**Comment by Jonathan-LeRoux** [comment]
That's great to hear! I'll close the ticket.
