### ISSUE TITLE
"(Optional)" Missing For Point 4 of Windows Installation Guide

### ISSUE THREAD

**Issue by ennomuller** [Jonathan-LeRoux/IguanaTex#61]

**Comment by Jonathan-LeRoux** [comment]
Technically, it's true that it's optional because there is a particular combination of LaTeX engine and output format that requires neither Ghostscript nor ImageMagick, but that's very limited. I'll try to come up with a wording that explains this clearly.

**Comment by Jonathan-LeRoux** [comment]
README now clarified.
