### ISSUE TITLE
编译代码时报错

### ISSUE THREAD

**Issue by haomes** [Jonathan-LeRoux/IguanaTex#62]
当我直接运行：
\documentclass{article}
\usepackage{amsmath}
\pagestyle{empty}
\begin{document}

$ G=(\mathcal{V},\mathcal{E}) $

\end{document}

报错：
'/Library/TeX/texbin/pdflatex' -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex
<img width="445" alt="image" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/82690723/6e2e01f2-d5ed-4a40-aa6a-dbbae6519361">

**Comment by Jonathan-LeRoux** [comment]
Please try to run with "Debug" checked, and also try to compile outside IguanaTex. On the Mac, you need to navigate to the temporary folder that's indicated in the edit window.

**Comment by jd730** [comment]
Hi @Jonathan-LeRoux  I am also facing this error. I used this program for several years and recently downlaoded again since I formatted the amcbook.

<img width="464" alt="image" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/9247850/d92344e3-6e9e-4fd2-a6a1-ec27fc1dbbfd">

**Comment by Jonathan-LeRoux** [comment]
Are you sure you followed the installation instructions? Did you use homebrew or manual installation?

**Comment by jd730** [comment]
I first tried manual installation since that is what I did several years ago but I was facing the error and I tried to use homebrew although it did not solve it. However, I haven't checked the path yet. I will check it.

**Comment by Jonathan-LeRoux** [comment]
I'm not familiar with TeXShop and typically use MacTeX. You should check that the command above (`/Library/TeX/texbin/pdflatex`) does exist. If so, try navigating to the temp folder indicated in the IguanaTex edit window, and running that command.

**Comment by Jonathan-LeRoux** [comment]
Can one of you check what you have under `/Library/TeX/texbin/`?

**Comment by jd730** [comment]
In my case, `pdflatex` is stored on `$USER/Library/TeXShop/bin` along with other files

<img width="1435" alt="image" src="https://github.com/Jonathan-LeRoux/IguanaTex/assets/9247850/14565865-73b4-4511-bbe7-ed5494392243">

**Comment by Jonathan-LeRoux** [comment]
I assume `/Library/TeX/texbin/` doesn't exist. Could you create a symlink from `/Library/TeX/texbin/` to `$USER/Library/TeXShop/bin`?

**Comment by Jonathan-LeRoux** [comment]
What's surprising to me is that [TeXShop says](https://pages.uoregon.edu/koch/texshop/obtaining.html) you're supposed to install a TeX installation such as MacTeX or TeX Live, so I'm not sure how you ended up with your distribution being under `$USER/Library/TeXShop/`. Can you confirm these aren't symlinks to somewhere else?

**Comment by Jonathan-LeRoux** [comment]
I just realized that you can probably solve this by simply specifying the path to your LaTeX executables folder in IguanaTex's Main Settings...

**Comment by jd730** [comment]
I think that is the first thing I tried before but I will try it again right now. Thanks for helping me!

**Comment by jd730** [comment]
It worked! The problem was `$USER/Library/TeXShop/bin` only has `pdfeuptex` and `pdfeptex` not `pdflatex`. I really apologize for my mistake and I really appreciate your help.
The correct path for me was `/usr/local/texlive/2023/bin/universal-darwin/`

**Comment by Jonathan-LeRoux** [comment]
Thanks for confirming! I'll clarify the README.
@haomes , did you have a similar issue?
