### ISSUE TITLE
Default shape color (e.g. white)

### ISSUE THREAD

**Issue by Splines** [Jonathan-LeRoux/IguanaTex#68]
For [YouTube videos](https://www.youtube.com/@splience), I'd like to keep my black background of the presentation. When pasting equations as shapes, I have to fill it with white color by hand (not much effort, but still one click / keystroke 😅).

It'd be amazing to have a setting in `Main settings` that controls the **default color for shapes**.

**Comment by Jonathan-LeRoux** [comment]
That's a good idea, let me see how I could implement that.
A workaround is to create a first shape with the settings you like, then copy/paste it and use the edit function to create a new shape from the old one, pasting the new code in. I use this a lot when I want to keep sizes consistent.

**Comment by Splines** [comment]
Nice workaround. But compared to copying the object from another slide and pasting it into a new one, then editing it, it's probably not quicker than filling the color with white for a newly generated equation (especially since I added `Shape fill` to the quick access menu bar). To keep sizes consistent, I usually don't scale the equations in PowerPoint and instead only change the `pt` sizes in your plugin.

**Comment by Jonathan-LeRoux** [comment]
I implemented the choice of color for the Fill of Shape objects. There are actually many other things one could set other than the Fill, but that would start to be quite complicated, so I'll leave it that.
The color is set in the editor window, and can be saved using the "Make Default" button. That default will be applied when generating new displays or converting an existing display to Shape. I also added the ability to change the color in the batch processing.
Here is a zip with the .pptm and .ppam: [IguanaTex_v1_61_1_20240726.zip](https://github.com/user-attachments/files/16397030/IguanaTex_v1_61_1_20240726.zip).
Please give it a try and let me know if you see any issue.

**Comment by Splines** [comment]
Wow, you're quick, thank you so much for the improvements. The default shape color works like a charm! Also see my feedback on #66 for the file path.

**Comment by Jonathan-LeRoux** [comment]
Fixed with [v1.62 release](https://github.com/Jonathan-LeRoux/IguanaTex/releases/tag/v1.62).
