### ISSUE TITLE
Error while running process

### ISSUE THREAD

**Issue by zonglunli7515** [Jonathan-LeRoux/IguanaTex#69]
![Screenshot 2024-07-23 at 16 47 04](https://github.com/user-attachments/assets/dfdd4605-adba-4e09-896d-558bf2c329c4)

Dear All,

I followed through the installation instructions but failed to generate the tex (see attached). Does anyone know how to fix it?

Thanks in advance for your help.

**Comment by Jonathan-LeRoux** [comment]
It could be many things.
I would copy the command and try to run it in a terminal after cd-ing to your temp folder.
It looks like you are using a relative Temp folder. I’d try to use the absolute one (it’s less painful on Mac because of permissions).

**Comment by zonglunli7515** [comment]
> It could be many things. I would copy the command and try to run it in a terminal after cd-ing to your temp folder. It looks like you are using a relative Temp folder. I’d try to use the absolute one (it’s less painful on Mac because of permissions).

Thanks for your speedy reply. I am relatively new to Mac so it would be very much appreciated if you could shed some light on what you just described. What do you mean by 'copy the command and try to run it in a terminal after cd-ing to your temp folder'? Do you suggest that I should copy the 'Temp. folder' path in terminal and run some command?

**Comment by Jonathan-LeRoux** [comment]
Yes, open a terminal, use "cd" to navigate to your "Temp folder", then copy and paste the command that appears in the "Error while running process" window in your picture (you can copy with the Copy button).

**Comment by zonglunli7515** [comment]
> Yes, open a terminal, use "cd" to navigate to your "Temp folder", then copy and paste the command that appears in the "Error while running process" window in your picture (you can copy with the Copy button).

It says 'zsh: no such file or directory: /Library/TeX/texbin/pdflatex'.

**Comment by Jonathan-LeRoux** [comment]
You need to find where your latex installation is. What does 'where pdflatex' give you?

**Comment by zonglunli7515** [comment]
> You need to find where your latex installation is. What does 'where pdflatex' give you?

Many thanks for the reminder. Yes, the Tex was incorrectly installed and now it seems to work.

**Comment by Jonathan-LeRoux** [comment]
Happy to hear!
