### ISSUE TITLE
Clarification on Supported PowerPoint Versions for IguanaTex (macOS)

### ISSUE THREAD

**Issue by johannahaffner** [Jonathan-LeRoux/IguanaTex#72]
I am experiencing an issue while using IguanaTex on macOS. Specifically, I'm encountering `runtime error '5' (Invalid procedure call or argument)` when trying to generate even simple LaTeX content through IguanaTex in PowerPoint.

**Environment:**
macOS version: 14.7 (23H124) (Sonoma)
PowerPoint version: 16.89.1 (24091630)
IguanaTex version: v1.61

**Problem:**
I have tried running a simple LaTeX example such as Hello World, but IguanaTex returns runtime error '5'.
I've attempted various troubleshooting steps, including:

- Reinstalling IguanaTex.
- Ensuring that Ghostscript is correctly installed and path is what is expected, repeated custom installation of MacTex
- Running commands manually to ensure that pdflatex and Ghostscript work as expected. 

Powerpoint does not have Full Disk Access on my system, but that is also something I would like to avoid.
As a next step, I was considering building from source.

**Questions:**
- Supported PowerPoint Versions:
The documentation states that IguanaTex supports "PowerPoint 2019 or Office 365." However, I found that version numbers for PowerPoint across versions (2016 to 2021 and Office 365) are often listed as 16.x.
Could you please clarify which specific versions or build numbers of PowerPoint (e.g., Office 365) are supported?
- Additional Debugging Recommendations:
Are there any additional debugging tools or logging options available that might help further isolate this issue?
Any help or insight into the exact versions of PowerPoint that work well with IguanaTex, or other suggestions, would be greatly appreciated!

**Additional Information:**
Output when executing commands directly in the shell:

- I can manually generate the .dvi, and from that I can generate .png and .pdf files that look as expected. 
- Generating a .svg raises a warning that Ghostscript is not found, even though other steps that also rely on Ghostscript work. 

<img width="540" alt="Screenshot 2024-10-11 at 10 20 21" src="https://github.com/user-attachments/assets/ee39c089-4197-4f04-8e12-2acf1cd73566">

- Without running commands manually, the only thing that is generated if I try to execute from within Powerpoint is the temporary .tex file.

Thank you very much for your time and for maintaining this tool!

**Comment by Jonathan-LeRoux** [comment]
Hi, 

I'm not aware of any version of Office 2019 or 365 that is not compatible. For 2016, it's specified in the Readme.

I agree that I should really have a dedicated section in the readme on how to debug, as I have probably written these instructions in 50 different messages😅
In the meantime, you can find instructions in [this comment](https://github.com/Jonathan-LeRoux/IguanaTex/issues/65#issuecomment-2170959986) for a recent issue.

**Comment by johannahaffner** [comment]
Thanks, I will try the VBA editor breakpoints! :)

**Comment by Jonathan-LeRoux** [comment]
Any luck?

**Comment by johannahaffner** [comment]
I couldn't get anything to show up in the Visual Basic Editor and then gave up.

I'm happy to try again sometime next week!

**Comment by johannahaffner** [comment]
Hi @Jonathan-LeRoux, 

since I no longer had Iguanatex on my computer, I installed afresh, this time using brew. I can now typeset simple equations, so it seems as though the problem is mostly fixed.

The paths do not appear to be correct, though - the path to libgs listed in the main settings does not exist.

**Comment by Jonathan-LeRoux** [comment]
These paths are just best guesses, you need to replace them with the correct paths. As explained in the README, you need to  open a terminal and use `locate libgs`.
I will replace the default with the current version installed by MacTeX (it so happens that I went through the installation process on a new MBA this morning).
I'll close this issue as it looks like this was a problem with the installation. Thanks!
