### ISSUE TITLE
Installing on OSX 10.13 (High Sierra) & Powerpoint 16.16.27 (File not found, out of memory and type mismatch errors)

### ISSUE THREAD

**Issue by aboev** [Jonathan-LeRoux/IguanaTex#73]
First of all, thanks a lot, IguanaTex is an awesome peace of software!
Below are some problems and solutions while installing IguanaTex on older OSX / PPT versions.
Unfortunately, I could not install IguanaTex v.1.61 (too many errors and silent failures), but after some fixing I managed to run IguanaTex v.1.59.1 successfully.

**Problem 1 - "File not found - libIguanaTexHelper.dylib"**
Solution on OSX < 10.14: Install [Swift 5 Runtime Support for Command Line Tools](https://support.apple.com/en-us/106446)

**Problem 2 - "Out of memory" error everywhere** (when opening GUI Forms)
Workaround: Comment out MakeWindowResizable function in pptm source code and rebuild ppam macros (export ppam)
  * Something is causing problem in this function, but I did not investigate what exactly and why.
```vba
Public Sub MakeFormResizable(currentForm As Variant)
    'Dim index As LongLong
    'MacResizableForms.Add currentForm
    'index = MacResizableForms.count
    'MacMakeFormResizable index, AddressOf MacDoResize, 0, 0
End Sub
```

**Problem 3 - "Type mismatch"**
Solution: set decimal separator "." in OSX regional settings

**Sidenote on sandbox**: Sandbox location is `~/Library/Containers/com.microsoft.Powerpoint/Data/` in Powerpoint 16.16, so it is better to set absolute path to temporary folder in order to prevent permission errors.

**P.S.** maybe problems 2 and 3 can be resolved more cleanly within IguanaTex source
**P.P.S.** debugging PPT macros is a painful process due to the lack of proper logging, misleading error messages, etc. However, if anyone else is stuck with older OSX/PPT and still excited to use IguanaTex, we can try to fix above mentioned problems together in a more proper manner.

**Comment by aboev** [comment]
See my solutions above

**Comment by Jonathan-LeRoux** [comment]
Thanks for reporting your findings! Maybe @tsung-ju has thoughts about how to expand compatibility to more versions.

Note that, back when I still used my 2009 iMac, I was able to run IguanaTex on High Sierra with PowerPoint 2019, so I think it's more the PowerPoint version than the OS's that is limiting in your case.

**Comment by tsung-ju** [comment]
Thanks for your thorough report and for taking the time to debug these issues!

#### Problem 1
The Swift runtime library is only installed by default on macOS 10.14 and above, so 10.13 users need to install it manually. I’ll add this to the installation instructions.

#### Problem 2
The VBA feature in Mac PowerPoint 2016 had several bugs, including issues with using `AddressOf` to reference VBA functions which window resizing and copy-paste relies on. A possible workaround we can do is to add a few `#If`s to comment out these features if the version is less than 2019.

#### Problem 3
I may have assumed the decimal separator to be "." somewhere in the code, but I'm not entirely sure..

**Comment by Jonathan-LeRoux** [comment]
Thanks @tsung-ju , I will add comments in the Readme too.

Re: 2, was this for all versions of 2016, or only the ones prior to what we say is the minimal version in the readme? It would be good not to remove capabilities for folks with later 2016 versions if not necessary.

@koppor , could you give us more details about when you saw problem 3? If possible, which line of code triggered it.

**Comment by koppor** [comment]
> @koppor , could you give us more details about when you saw problem 3? If possible, which line of code triggered it. 

I am on Windows. 😅

**Comment by Jonathan-LeRoux** [comment]
Haha, sorry, that's what I get for using the GitHub app, I blindly selected another handle that it was suggesting and I couldn't see the other comments while typing 🤣
Alright, the question is for @aboev 🤗

**Comment by Jonathan-LeRoux** [comment]
Also, @aboev, could you give more details about what you are suggesting here:
"Sidenote on sandbox: Sandbox location is ~/Library/Containers/com.microsoft.Powerpoint/Data/ in Powerpoint 16.16, so it is better to set absolute path to temporary folder in order to prevent permission errors."

**Comment by aboev** [comment]
So, regarding problem 3, it is caused here:
```vba
Private Function BoundingBoxString(ByVal BBXFile As String) As String
            '...
            llx = CDbl(TextSplit(1)) - 0.1
            lly = CDbl(TextSplit(2)) - 0.1
            urx = CDbl(TextSplit(3)) + 0.1
            ury = CDbl(TextSplit(4)) + 0.1
            '...
...
```
Regarding the sandbox path, in my case none of following values for temp path - `.` `./` not even empty string worked unless I saved the ppt first (as stated in your readme). However, if I set the temporary path to the proper sandbox location as mentioned above, I can use IguanaTex feaures even without saving the ppt, which is more convenient.

**Comment by Jonathan-LeRoux** [comment]
This is very helpful. After going down a rabbit hole, I finally remembered that this problem had been discussed in Issue https://github.com/Jonathan-LeRoux/IguanaTex/issues/18, and you're using a version where I had introduced a bug by replacing `Val` with `CDbl`. `CDbl` is locale-dependent, but in this instance we don't want to be locale-dependent as we're looking at the output of Ghostscript, which always uses US format.

I would thus suggest trying to make a more recent version work, or importing that function from a more recent version.

**Comment by aboev** [comment]
> I would thus suggest trying to make a more recent version work

Yes, I did exactly that. So, final solution is to install latest version (IguanaTex v.1.61), which is not prone to "type mismatch" errors, but requires commenting below parts of code (due to `AddressOf` bug, which causes "out of memory"):

<h5 a><strong><code>MacUtils.bas</code></strong></h5>

```vba
Public Sub MacEnableCopyPaste(ByRef currentForm As Variant)
    ' MacEnableCopyPaste_Native ObjPtr(currentForm), AddressOf MacDoCopyPaste, 0, 0
End Sub

Public Sub MacEnableAccelerators(ByRef currentForm As Variant)
    ' MacEnableAccelerators_Native ObjPtr(currentForm), AddressOf MacDoAccelerator, 0, 0
End Sub
```

<h5 a><strong><code>Utils.bas</code></strong></h5>

```vba
Public Sub MakeFormResizable(currentForm As Variant)
    ' MacMakeFormResizable ObjPtr(currentForm), AddressOf MacDoResize, 0, 0
End Sub
```

Of course, it's nice to have resizable and copy-pastable forms, but given Powerpoint 16.16.27 limitations, it's good enough.
