### ISSUE TITLE
(Re)add mouse wheel support

### ISSUE THREAD

**Issue by koppor** [Jonathan-LeRoux/IguanaTex#76]
Refs https://github.com/Jonathan-LeRoux/IguanaTex/issues/12#issuecomment-704642824

Mouse wheel scrolling of the "latex code" area does not work. Meaning: If I use the mouse wheel while hovering on that field, nothing happens.

**Comment by Jonathan-LeRoux** [comment]
It works for me... We need to figure out why it doesn't work for you. Note that the comment you referred to is old and should have been addressed. 

I've noticed in the past that sometimes the scrolling bar doesn't appear, but I haven't seen this in a long time and couldn't reproduce it regularly. I'm wondering if maybe you're hitting this kind of situation here.

**Comment by koppor** [comment]
Scrollbars appear:

![image](https://github.com/user-attachments/assets/0562ba8c-9b3f-40a9-95e3-3ed078d3b7fa)

- Microsoft Windows [Version 10.0.19045.5073]
- Microsoft® PowerPoint® 2019 MSO (Version 2409 Build 16.0.18025.20160) 32-bit

**Comment by Jonathan-LeRoux** [comment]
Oh, you're talking about the error window! It's true that this isn't implemented. I can easily add it, I think it's only a matter of integrating to the ErrorForm the code around [this line](https://github.com/Jonathan-LeRoux/IguanaTex/blob/f08a71d619234916e6d795f30cd632ff5daf3f3a/LogFileViewer.frm#L68).

**Comment by Jonathan-LeRoux** [comment]
Please try the version in [IguanaTex_v1_62_20241102.zip](https://github.com/user-attachments/files/17608882/IguanaTex_v1_62_20241102.zip), it should fix this issue and https://github.com/Jonathan-LeRoux/IguanaTex/issues/77.

**Comment by koppor** [comment]
> Please try the version in [IguanaTex_v1_62_20241102.zip](https://github.com/user-attachments/files/17608882/IguanaTex_v1_62_20241102.zip), it should fix this issue and #77.

Thank you for the quick reply. I tried to compile `IguanaTex_v1_62.pptm` to `*.ppam`, but I have an compile error in `ErrorForm`

![image](https://github.com/user-attachments/assets/21c497e1-4412-428b-946a-c99c5b548558)

I am stuck somehow 😅

**Comment by Jonathan-LeRoux** [comment]
My bad, I got totally confused between the ErrorForm, which doesn't have any scrollable area, and the LogFileViewer, which is what you were talking about. But the LogFileViewer should already have the ability to scroll with the mouse wheel. It works on my end. So we're back to needing to figure out why it doesn't work for you.

This is really hard to debug because you can't really put a breakpoint near HookListBoxScroll, it will just crash PowerPoint...

Can you scroll in the main IguanaTex window?

**Comment by Jonathan-LeRoux** [comment]
Here is a version without the scroll fix, but which fixes https://github.com/Jonathan-LeRoux/IguanaTex/issues/77: [IguanaTex_v1_62_20241103.zip](https://github.com/user-attachments/files/17610902/IguanaTex_v1_62_20241103.zip)

**Comment by Jonathan-LeRoux** [comment]
The only thing I can think of is that your PowerPoint is 32-bit. The scrolling functions are supposed to work both on 32 and 64-bit, but I have no way to test that...

**Comment by koppor** [comment]
Then, I close. In case I manage to install PowerPoint 64bit - and I encounter this issue, I will reopen.

**Comment by Jonathan-LeRoux** [comment]
Please keep us updated!
