### ISSUE TITLE
Generate Error: "pdflatex" -shell-escape -interaction=batchmode IguanaTex_tmp.tex

### ISSUE THREAD

**Issue by TheBaluu** [Jonathan-LeRoux/IguanaTex#78]
Hello,

I have seen in two older posts to the same issue however they seem to have found solutions.
https://github.com/Jonathan-LeRoux/IguanaTex/issues/48
https://github.com/Jonathan-LeRoux/IguanaTex/issues/57

After clicking on "Generate" an error message pops up (also in debug mode).
With the LaTeX-Enigne latex (DVI):
"pdflatex" -output-format dvi -shell-escape -interaction=batchmode IguanaTex_tmp.tex 

With the LaTeX-Enigne pdflatex:
"pdflatex" -shell-escape -interaction=batchmode IguanaTex_tmp.tex

I can however run the commands in a cmd window in the C:\Temp folder. Executing the command in the command line works just fine and the DVI (or PDF) is generated.

What I don't understand is how the others resolved this issue. Do you know what I could be missing?

I have Windows 10, Office 365, latest MikTex version. However I did not install GhostScript nor ImageMagick or TeX2img

**Comment by Jonathan-LeRoux** [comment]
It's hard to tell. It could be as in #48 that your admin is blocking Office from starting processes.
I'm not sure how the user in #57 ended up fixing their issue, they said they went through the installation steps again as they were missing a few things.

**Comment by TheBaluu** [comment]
Hey, just wanted to let you know that it's working now. It seems like restarting the computer did the job. 

Anyway, Thanks for your great Add-In
