### ISSUE TITLE
can not use unicode characters inside math mode

### ISSUE THREAD

**Issue by jdhao** [Jonathan-LeRoux/IguanaTex#9]
I want to use some Chinese characters inside math mode. The following code compiles correctly in command line using `pdflatex`:

```
\documentclass[UTF8]{ctexart}
\usepackage{amsmath}
\pagestyle{empty}

\begin{document}

$\text{比例} = \frac{\text{部分}}{\text{全部}}$

\end{document}
```

But when I tried to generate an image inside the powerpoint, I got the following error

> Error while using ghostscript to compute the bounding box Is your
path correct?

**Comment by Jonathan-LeRoux** [comment]
This works on my system. Can you try clicking the Debug check box, see where it crashes, then run that step in the command line (you should be able to paste the command, it's saved to clipboard)?

**Comment by jdhao** [comment]
@Jonathan-LeRoux , thanks for your suggestion. I have figured out that it is because I have not set the correct path for GhostScript and ImageMagick. After I set their paths correctly, I was able to generate the equation successfully.
